export type Province = {
  id: number
  name: string
}

export type City = {
  id: number
  provinceID: number
  name: string
  type: 'Kabupaten' | 'Kota'
}

export const INDONESIAN_PROVINCES: Province[] = [
  { id: 11, name: 'Aceh (NAD)' },
  { id: 12, name: 'Sumatera Utara' },
  { id: 13, name: 'Sumatera Barat' },
  { id: 14, name: 'Riau' },
  { id: 15, name: 'Jambi' },
  { id: 16, name: 'Sumatera Selatan' },
  { id: 17, name: 'Bengkulu' },
  { id: 18, name: 'Lampung' },
  { id: 19, name: 'Kepulauan Bangka Belitung' },
  { id: 21, name: 'Kepulauan Riau' },
  { id: 31, name: 'DKI Jakarta' },
  { id: 32, name: 'Jawa Barat' },
  { id: 33, name: 'Jawa Tengah' },
  { id: 34, name: 'DI Yogyakarta' },
  { id: 35, name: 'Jawa Timur' },
  { id: 36, name: 'Banten' },
  { id: 51, name: 'Bali' },
  { id: 52, name: 'Nusa Tenggara Barat' },
  { id: 53, name: 'Nusa Tenggara Timur' },
  { id: 61, name: 'Kalimantan Barat' },
  { id: 62, name: 'Kalimantan Tengah' },
  { id: 63, name: 'Kalimantan Selatan' },
  { id: 64, name: 'Kalimantan Timur' },
  { id: 65, name: 'Kalimantan Utara' },
  { id: 71, name: 'Sulawesi Utara' },
  { id: 72, name: 'Sulawesi Tengah' },
  { id: 73, name: 'Sulawesi Selatan' },
  { id: 74, name: 'Sulawesi Tenggara' },
  { id: 75, name: 'Gorontalo' },
  { id: 76, name: 'Sulawesi Barat' },
  { id: 81, name: 'Maluku' },
  { id: 82, name: 'Maluku Utara' },
  { id: 91, name: 'Papua' },
  { id: 92, name: 'Papua Barat' },
  { id: 93, name: 'Papua Selatan' },
  { id: 94, name: 'Papua Tengah' },
  { id: 95, name: 'Papua Pegunungan' },
  { id: 96, name: 'Papua Barat Daya' },
]

export const INDONESIAN_CITIES: City[] = [
  { id: 1101, provinceID: 11, name: 'Simeulue', type: 'Kabupaten' as const },
  { id: 1102, provinceID: 11, name: 'Aceh Singkil', type: 'Kabupaten' as const },
  { id: 1103, provinceID: 11, name: 'Aceh Selatan', type: 'Kabupaten' as const },
  { id: 1104, provinceID: 11, name: 'Aceh Tenggara', type: 'Kabupaten' as const },
  { id: 1105, provinceID: 11, name: 'Aceh Timur', type: 'Kabupaten' as const },
  { id: 1106, provinceID: 11, name: 'Aceh Tengah', type: 'Kabupaten' as const },
  { id: 1107, provinceID: 11, name: 'Aceh Barat', type: 'Kabupaten' as const },
  { id: 1108, provinceID: 11, name: 'Aceh Besar', type: 'Kabupaten' as const },
  { id: 1109, provinceID: 11, name: 'Pidie', type: 'Kabupaten' as const },
  { id: 1110, provinceID: 11, name: 'Bireuen', type: 'Kabupaten' as const },
  { id: 1111, provinceID: 11, name: 'Aceh Utara', type: 'Kabupaten' as const },
  { id: 1112, provinceID: 11, name: 'Aceh Barat Daya', type: 'Kabupaten' as const },
  { id: 1113, provinceID: 11, name: 'Gayo Lues', type: 'Kabupaten' as const },
  { id: 1114, provinceID: 11, name: 'Aceh Tamiang', type: 'Kabupaten' as const },
  { id: 1115, provinceID: 11, name: 'Nagan Raya', type: 'Kabupaten' as const },
  { id: 1116, provinceID: 11, name: 'Aceh Jaya', type: 'Kabupaten' as const },
  { id: 1117, provinceID: 11, name: 'Bener Meriah', type: 'Kabupaten' as const },
  { id: 1118, provinceID: 11, name: 'Pidie Jaya', type: 'Kabupaten' as const },
  { id: 1171, provinceID: 11, name: 'Banda Aceh', type: 'Kota' as const },
  { id: 1172, provinceID: 11, name: 'Sabang', type: 'Kota' as const },
  { id: 1173, provinceID: 11, name: 'Lhokseumawe', type: 'Kota' as const },
  { id: 1174, provinceID: 11, name: 'Langsa', type: 'Kota' as const },
  { id: 1175, provinceID: 11, name: 'Subulussalam', type: 'Kota' as const },
  { id: 1201, provinceID: 12, name: 'Nias', type: 'Kabupaten' as const },
  { id: 1202, provinceID: 12, name: 'Mandailing Natal', type: 'Kabupaten' as const },
  { id: 1203, provinceID: 12, name: 'Tapanuli Selatan', type: 'Kabupaten' as const },
  { id: 1204, provinceID: 12, name: 'Tapanuli Tengah', type: 'Kabupaten' as const },
  { id: 1205, provinceID: 12, name: 'Tapanuli Utara', type: 'Kabupaten' as const },
  { id: 1206, provinceID: 12, name: 'Toba Samosir', type: 'Kabupaten' as const },
  { id: 1207, provinceID: 12, name: 'Labuhan Batu', type: 'Kabupaten' as const },
  { id: 1208, provinceID: 12, name: 'Asahan', type: 'Kabupaten' as const },
  { id: 1209, provinceID: 12, name: 'Simalungun', type: 'Kabupaten' as const },
  { id: 1210, provinceID: 12, name: 'Dairi', type: 'Kabupaten' as const },
  { id: 1211, provinceID: 12, name: 'Karo', type: 'Kabupaten' as const },
  { id: 1212, provinceID: 12, name: 'Deliserdang', type: 'Kabupaten' as const },
  { id: 1213, provinceID: 12, name: 'Langkat', type: 'Kabupaten' as const },
  { id: 1214, provinceID: 12, name: 'Nias Selatan', type: 'Kabupaten' as const },
  { id: 1215, provinceID: 12, name: 'Humbang Hasundutan', type: 'Kabupaten' as const },
  { id: 1216, provinceID: 12, name: 'Pakpak Bharat', type: 'Kabupaten' as const },
  { id: 1217, provinceID: 12, name: 'Samosir', type: 'Kabupaten' as const },
  { id: 1218, provinceID: 12, name: 'Serdang Bedagai', type: 'Kabupaten' as const },
  { id: 1219, provinceID: 12, name: 'Batu Bara', type: 'Kabupaten' as const },
  { id: 1220, provinceID: 12, name: 'Padang Lawas Utara', type: 'Kabupaten' as const },
  { id: 1221, provinceID: 12, name: 'Padang Lawas', type: 'Kabupaten' as const },
  { id: 1222, provinceID: 12, name: 'Labuhan Batu Selatan', type: 'Kabupaten' as const },
  { id: 1223, provinceID: 12, name: 'Labuhan Batu Utara', type: 'Kabupaten' as const },
  { id: 1224, provinceID: 12, name: 'Nias Utara', type: 'Kabupaten' as const },
  { id: 1225, provinceID: 12, name: 'Nias Barat', type: 'Kabupaten' as const },
  { id: 1271, provinceID: 12, name: 'Sibolga', type: 'Kota' as const },
  { id: 1272, provinceID: 12, name: 'Tanjung Balai', type: 'Kota' as const },
  { id: 1273, provinceID: 12, name: 'Pematang Siantar', type: 'Kota' as const },
  { id: 1274, provinceID: 12, name: 'Tebing Tinggi', type: 'Kota' as const },
  { id: 1275, provinceID: 12, name: 'Medan', type: 'Kota' as const },
  { id: 1276, provinceID: 12, name: 'Binjai', type: 'Kota' as const },
  { id: 1277, provinceID: 12, name: 'Padangsidimpuan', type: 'Kota' as const },
  { id: 1278, provinceID: 12, name: 'Gunungsitoli', type: 'Kota' as const },
  { id: 1301, provinceID: 13, name: 'Kepulauan Mentawai', type: 'Kabupaten' as const },
  { id: 1302, provinceID: 13, name: 'Pesisir Selatan', type: 'Kabupaten' as const },
  { id: 1303, provinceID: 13, name: 'Solok', type: 'Kabupaten' as const },
  { id: 1304, provinceID: 13, name: 'Sijunjung', type: 'Kabupaten' as const },
  { id: 1305, provinceID: 13, name: 'Tanah Datar', type: 'Kabupaten' as const },
  { id: 1306, provinceID: 13, name: 'Padang Pariaman', type: 'Kabupaten' as const },
  { id: 1307, provinceID: 13, name: 'Agam', type: 'Kabupaten' as const },
  { id: 1308, provinceID: 13, name: 'Lima Puluh Kota', type: 'Kabupaten' as const },
  { id: 1309, provinceID: 13, name: 'Pasaman', type: 'Kabupaten' as const },
  { id: 1310, provinceID: 13, name: 'Solok Selatan', type: 'Kabupaten' as const },
  { id: 1311, provinceID: 13, name: 'Dharmasraya', type: 'Kabupaten' as const },
  { id: 1312, provinceID: 13, name: 'Pasaman Barat', type: 'Kabupaten' as const },
  { id: 1371, provinceID: 13, name: 'Padang', type: 'Kota' as const },
  { id: 1372, provinceID: 13, name: 'Solok', type: 'Kota' as const },
  { id: 1373, provinceID: 13, name: 'Sawah Lunto', type: 'Kota' as const },
  { id: 1374, provinceID: 13, name: 'Padang Panjang', type: 'Kota' as const },
  { id: 1375, provinceID: 13, name: 'Bukittinggi', type: 'Kota' as const },
  { id: 1376, provinceID: 13, name: 'Payakumbuh', type: 'Kota' as const },
  { id: 1377, provinceID: 13, name: 'Pariaman', type: 'Kota' as const },
  { id: 1401, provinceID: 14, name: 'Kuantan Singingi', type: 'Kabupaten' as const },
  { id: 1402, provinceID: 14, name: 'Indragiri Hulu', type: 'Kabupaten' as const },
  { id: 1403, provinceID: 14, name: 'Indragiri Hilir', type: 'Kabupaten' as const },
  { id: 1404, provinceID: 14, name: 'Pelalawan', type: 'Kabupaten' as const },
  { id: 1405, provinceID: 14, name: 'S I A K', type: 'Kabupaten' as const },
  { id: 1406, provinceID: 14, name: 'Kampar', type: 'Kabupaten' as const },
  { id: 1407, provinceID: 14, name: 'Rokan Hulu', type: 'Kabupaten' as const },
  { id: 1408, provinceID: 14, name: 'Bengkalis', type: 'Kabupaten' as const },
  { id: 1409, provinceID: 14, name: 'Rokan Hilir', type: 'Kabupaten' as const },
  { id: 1410, provinceID: 14, name: 'Kepulauan Meranti', type: 'Kabupaten' as const },
  { id: 1471, provinceID: 14, name: 'Pekanbaru', type: 'Kota' as const },
  { id: 1473, provinceID: 14, name: 'Dumai', type: 'Kota' as const },
  { id: 1501, provinceID: 15, name: 'Kerinci', type: 'Kabupaten' as const },
  { id: 1502, provinceID: 15, name: 'Merangin', type: 'Kabupaten' as const },
  { id: 1503, provinceID: 15, name: 'Sarolangun', type: 'Kabupaten' as const },
  { id: 1504, provinceID: 15, name: 'Batang Hari', type: 'Kabupaten' as const },
  { id: 1505, provinceID: 15, name: 'Muaro Jambi', type: 'Kabupaten' as const },
  { id: 1506, provinceID: 15, name: 'Tanjung Jabung Timur', type: 'Kabupaten' as const },
  { id: 1507, provinceID: 15, name: 'Tanjung Jabung Barat', type: 'Kabupaten' as const },
  { id: 1508, provinceID: 15, name: 'Tebo', type: 'Kabupaten' as const },
  { id: 1509, provinceID: 15, name: 'Bungo', type: 'Kabupaten' as const },
  { id: 1571, provinceID: 15, name: 'Jambi', type: 'Kota' as const },
  { id: 1572, provinceID: 15, name: 'Sungai Penuh', type: 'Kota' as const },
  { id: 1601, provinceID: 16, name: 'Ogan Komering Ulu', type: 'Kabupaten' as const },
  { id: 1602, provinceID: 16, name: 'Ogan Komering Ilir', type: 'Kabupaten' as const },
  { id: 1603, provinceID: 16, name: 'Muara Enim', type: 'Kabupaten' as const },
  { id: 1604, provinceID: 16, name: 'Lahat', type: 'Kabupaten' as const },
  { id: 1605, provinceID: 16, name: 'Musi Rawas', type: 'Kabupaten' as const },
  { id: 1606, provinceID: 16, name: 'Musi Banyuasin', type: 'Kabupaten' as const },
  { id: 1607, provinceID: 16, name: 'Banyuasin', type: 'Kabupaten' as const },
  { id: 1608, provinceID: 16, name: 'Ogan Komering Ulu Selatan', type: 'Kabupaten' as const },
  { id: 1609, provinceID: 16, name: 'Ogan Komering Ulu Timur', type: 'Kabupaten' as const },
  { id: 1610, provinceID: 16, name: 'Ogan Ilir', type: 'Kabupaten' as const },
  { id: 1611, provinceID: 16, name: 'Empat Lawang', type: 'Kabupaten' as const },
  { id: 1612, provinceID: 16, name: 'Penukal Abab Lematang Ilir', type: 'Kabupaten' as const },
  { id: 1613, provinceID: 16, name: 'Musi Rawas Utara', type: 'Kabupaten' as const },
  { id: 1671, provinceID: 16, name: 'Palembang', type: 'Kota' as const },
  { id: 1672, provinceID: 16, name: 'Prabumulih', type: 'Kota' as const },
  { id: 1673, provinceID: 16, name: 'Pagar Alam', type: 'Kota' as const },
  { id: 1674, provinceID: 16, name: 'Lubuklinggau', type: 'Kota' as const },
  { id: 1701, provinceID: 17, name: 'Bengkulu Selatan', type: 'Kabupaten' as const },
  { id: 1702, provinceID: 17, name: 'Rejang Lebong', type: 'Kabupaten' as const },
  { id: 1703, provinceID: 17, name: 'Bengkulu Utara', type: 'Kabupaten' as const },
  { id: 1704, provinceID: 17, name: 'Kaur', type: 'Kabupaten' as const },
  { id: 1705, provinceID: 17, name: 'Seluma', type: 'Kabupaten' as const },
  { id: 1706, provinceID: 17, name: 'Mukomuko', type: 'Kabupaten' as const },
  { id: 1707, provinceID: 17, name: 'Lebong', type: 'Kabupaten' as const },
  { id: 1708, provinceID: 17, name: 'Kepahiang', type: 'Kabupaten' as const },
  { id: 1709, provinceID: 17, name: 'Bengkulu Tengah', type: 'Kabupaten' as const },
  { id: 1771, provinceID: 17, name: 'Bengkulu', type: 'Kota' as const },
  { id: 1801, provinceID: 18, name: 'Lampung Barat', type: 'Kabupaten' as const },
  { id: 1802, provinceID: 18, name: 'Tanggamus', type: 'Kabupaten' as const },
  { id: 1803, provinceID: 18, name: 'Lampung Selatan', type: 'Kabupaten' as const },
  { id: 1804, provinceID: 18, name: 'Lampung Timur', type: 'Kabupaten' as const },
  { id: 1805, provinceID: 18, name: 'Lampung Tengah', type: 'Kabupaten' as const },
  { id: 1806, provinceID: 18, name: 'Lampung Utara', type: 'Kabupaten' as const },
  { id: 1807, provinceID: 18, name: 'Way Kanan', type: 'Kabupaten' as const },
  { id: 1808, provinceID: 18, name: 'Tulangbawang', type: 'Kabupaten' as const },
  { id: 1809, provinceID: 18, name: 'Pesawaran', type: 'Kabupaten' as const },
  { id: 1810, provinceID: 18, name: 'Pringsewu', type: 'Kabupaten' as const },
  { id: 1811, provinceID: 18, name: 'Mesuji', type: 'Kabupaten' as const },
  { id: 1812, provinceID: 18, name: 'Tulang Bawang Barat', type: 'Kabupaten' as const },
  { id: 1813, provinceID: 18, name: 'Pesisir Barat', type: 'Kabupaten' as const },
  { id: 1871, provinceID: 18, name: 'Bandar Lampung', type: 'Kota' as const },
  { id: 1872, provinceID: 18, name: 'Metro', type: 'Kota' as const },
  { id: 1901, provinceID: 19, name: 'Bangka', type: 'Kabupaten' as const },
  { id: 1902, provinceID: 19, name: 'Belitung', type: 'Kabupaten' as const },
  { id: 1903, provinceID: 19, name: 'Bangka Barat', type: 'Kabupaten' as const },
  { id: 1904, provinceID: 19, name: 'Bangka Tengah', type: 'Kabupaten' as const },
  { id: 1905, provinceID: 19, name: 'Bangka Selatan', type: 'Kabupaten' as const },
  { id: 1906, provinceID: 19, name: 'Belitung Timur', type: 'Kabupaten' as const },
  { id: 1971, provinceID: 19, name: 'Pangkal Pinang', type: 'Kota' as const },
  { id: 2101, provinceID: 21, name: 'Karimun', type: 'Kabupaten' as const },
  { id: 2102, provinceID: 21, name: 'Bintan', type: 'Kabupaten' as const },
  { id: 2103, provinceID: 21, name: 'Natuna', type: 'Kabupaten' as const },
  { id: 2104, provinceID: 21, name: 'Lingga', type: 'Kabupaten' as const },
  { id: 2105, provinceID: 21, name: 'Kepulauan Anambas', type: 'Kabupaten' as const },
  { id: 2171, provinceID: 21, name: 'Batam', type: 'Kota' as const },
  { id: 2172, provinceID: 21, name: 'Tanjung Pinang', type: 'Kota' as const },
  { id: 3101, provinceID: 31, name: 'Kepulauan Seribu', type: 'Kabupaten' as const },
  { id: 3171, provinceID: 31, name: 'Jakarta Selatan', type: 'Kota' as const },
  { id: 3172, provinceID: 31, name: 'Jakarta Timur', type: 'Kota' as const },
  { id: 3173, provinceID: 31, name: 'Jakarta Pusat', type: 'Kota' as const },
  { id: 3174, provinceID: 31, name: 'Jakarta Barat', type: 'Kota' as const },
  { id: 3175, provinceID: 31, name: 'Jakarta Utara', type: 'Kota' as const },
  { id: 3201, provinceID: 32, name: 'Bogor', type: 'Kabupaten' as const },
  { id: 3202, provinceID: 32, name: 'Sukabumi', type: 'Kabupaten' as const },
  { id: 3203, provinceID: 32, name: 'Cianjur', type: 'Kabupaten' as const },
  { id: 3204, provinceID: 32, name: 'Bandung', type: 'Kabupaten' as const },
  { id: 3205, provinceID: 32, name: 'Garut', type: 'Kabupaten' as const },
  { id: 3206, provinceID: 32, name: 'Tasikmalaya', type: 'Kabupaten' as const },
  { id: 3207, provinceID: 32, name: 'Ciamis', type: 'Kabupaten' as const },
  { id: 3208, provinceID: 32, name: 'Kuningan', type: 'Kabupaten' as const },
  { id: 3209, provinceID: 32, name: 'Cirebon', type: 'Kabupaten' as const },
  { id: 3210, provinceID: 32, name: 'Majalengka', type: 'Kabupaten' as const },
  { id: 3211, provinceID: 32, name: 'Sumedang', type: 'Kabupaten' as const },
  { id: 3212, provinceID: 32, name: 'Indramayu', type: 'Kabupaten' as const },
  { id: 3213, provinceID: 32, name: 'Subang', type: 'Kabupaten' as const },
  { id: 3214, provinceID: 32, name: 'Purwakarta', type: 'Kabupaten' as const },
  { id: 3215, provinceID: 32, name: 'Karawang', type: 'Kabupaten' as const },
  { id: 3216, provinceID: 32, name: 'Bekasi', type: 'Kabupaten' as const },
  { id: 3217, provinceID: 32, name: 'Bandung Barat', type: 'Kabupaten' as const },
  { id: 3218, provinceID: 32, name: 'Pangandaran', type: 'Kabupaten' as const },
  { id: 3271, provinceID: 32, name: 'Bogor', type: 'Kota' as const },
  { id: 3272, provinceID: 32, name: 'Sukabumi', type: 'Kota' as const },
  { id: 3273, provinceID: 32, name: 'Bandung', type: 'Kota' as const },
  { id: 3274, provinceID: 32, name: 'Cirebon', type: 'Kota' as const },
  { id: 3275, provinceID: 32, name: 'Bekasi', type: 'Kota' as const },
  { id: 3276, provinceID: 32, name: 'Depok', type: 'Kota' as const },
  { id: 3277, provinceID: 32, name: 'Cimahi', type: 'Kota' as const },
  { id: 3278, provinceID: 32, name: 'Tasikmalaya', type: 'Kota' as const },
  { id: 3279, provinceID: 32, name: 'Banjar', type: 'Kota' as const },
  { id: 3301, provinceID: 33, name: 'Cilacap', type: 'Kabupaten' as const },
  { id: 3302, provinceID: 33, name: 'Banyumas', type: 'Kabupaten' as const },
  { id: 3303, provinceID: 33, name: 'Purbalingga', type: 'Kabupaten' as const },
  { id: 3304, provinceID: 33, name: 'Banjarnegara', type: 'Kabupaten' as const },
  { id: 3305, provinceID: 33, name: 'Kebumen', type: 'Kabupaten' as const },
  { id: 3306, provinceID: 33, name: 'Purworejo', type: 'Kabupaten' as const },
  { id: 3307, provinceID: 33, name: 'Wonosobo', type: 'Kabupaten' as const },
  { id: 3308, provinceID: 33, name: 'Magelang', type: 'Kabupaten' as const },
  { id: 3309, provinceID: 33, name: 'Boyolali', type: 'Kabupaten' as const },
  { id: 3310, provinceID: 33, name: 'Klaten', type: 'Kabupaten' as const },
  { id: 3311, provinceID: 33, name: 'Sukoharjo', type: 'Kabupaten' as const },
  { id: 3312, provinceID: 33, name: 'Wonogiri', type: 'Kabupaten' as const },
  { id: 3313, provinceID: 33, name: 'Karanganyar', type: 'Kabupaten' as const },
  { id: 3314, provinceID: 33, name: 'Sragen', type: 'Kabupaten' as const },
  { id: 3315, provinceID: 33, name: 'Grobogan', type: 'Kabupaten' as const },
  { id: 3316, provinceID: 33, name: 'Blora', type: 'Kabupaten' as const },
  { id: 3317, provinceID: 33, name: 'Rembang', type: 'Kabupaten' as const },
  { id: 3318, provinceID: 33, name: 'Pati', type: 'Kabupaten' as const },
  { id: 3319, provinceID: 33, name: 'Kudus', type: 'Kabupaten' as const },
  { id: 3320, provinceID: 33, name: 'Jepara', type: 'Kabupaten' as const },
  { id: 3321, provinceID: 33, name: 'Demak', type: 'Kabupaten' as const },
  { id: 3322, provinceID: 33, name: 'Semarang', type: 'Kabupaten' as const },
  { id: 3323, provinceID: 33, name: 'Temanggung', type: 'Kabupaten' as const },
  { id: 3324, provinceID: 33, name: 'Kendal', type: 'Kabupaten' as const },
  { id: 3325, provinceID: 33, name: 'Batang', type: 'Kabupaten' as const },
  { id: 3326, provinceID: 33, name: 'Pekalongan', type: 'Kabupaten' as const },
  { id: 3327, provinceID: 33, name: 'Pemalang', type: 'Kabupaten' as const },
  { id: 3328, provinceID: 33, name: 'Tegal', type: 'Kabupaten' as const },
  { id: 3329, provinceID: 33, name: 'Brebes', type: 'Kabupaten' as const },
  { id: 3371, provinceID: 33, name: 'Magelang', type: 'Kota' as const },
  { id: 3372, provinceID: 33, name: 'Surakarta', type: 'Kota' as const },
  { id: 3373, provinceID: 33, name: 'Salatiga', type: 'Kota' as const },
  { id: 3374, provinceID: 33, name: 'Semarang', type: 'Kota' as const },
  { id: 3375, provinceID: 33, name: 'Pekalongan', type: 'Kota' as const },
  { id: 3376, provinceID: 33, name: 'Tegal', type: 'Kota' as const },
  { id: 3401, provinceID: 34, name: 'Kulon Progo', type: 'Kabupaten' as const },
  { id: 3402, provinceID: 34, name: 'Bantul', type: 'Kabupaten' as const },
  { id: 3403, provinceID: 34, name: 'Gunung Kidul', type: 'Kabupaten' as const },
  { id: 3404, provinceID: 34, name: 'Sleman', type: 'Kabupaten' as const },
  { id: 3471, provinceID: 34, name: 'Yogyakarta', type: 'Kota' as const },
  { id: 3501, provinceID: 35, name: 'Pacitan', type: 'Kabupaten' as const },
  { id: 3502, provinceID: 35, name: 'Ponorogo', type: 'Kabupaten' as const },
  { id: 3503, provinceID: 35, name: 'Trenggalek', type: 'Kabupaten' as const },
  { id: 3504, provinceID: 35, name: 'Tulungagung', type: 'Kabupaten' as const },
  { id: 3505, provinceID: 35, name: 'Blitar', type: 'Kabupaten' as const },
  { id: 3506, provinceID: 35, name: 'Kediri', type: 'Kabupaten' as const },
  { id: 3507, provinceID: 35, name: 'Malang', type: 'Kabupaten' as const },
  { id: 3508, provinceID: 35, name: 'Lumajang', type: 'Kabupaten' as const },
  { id: 3509, provinceID: 35, name: 'Jember', type: 'Kabupaten' as const },
  { id: 3510, provinceID: 35, name: 'Banyuwangi', type: 'Kabupaten' as const },
  { id: 3511, provinceID: 35, name: 'Bondowoso', type: 'Kabupaten' as const },
  { id: 3512, provinceID: 35, name: 'Situbondo', type: 'Kabupaten' as const },
  { id: 3513, provinceID: 35, name: 'Probolinggo', type: 'Kabupaten' as const },
  { id: 3514, provinceID: 35, name: 'Pasuruan', type: 'Kabupaten' as const },
  { id: 3515, provinceID: 35, name: 'Sidoarjo', type: 'Kabupaten' as const },
  { id: 3516, provinceID: 35, name: 'Mojokerto', type: 'Kabupaten' as const },
  { id: 3517, provinceID: 35, name: 'Jombang', type: 'Kabupaten' as const },
  { id: 3518, provinceID: 35, name: 'Nganjuk', type: 'Kabupaten' as const },
  { id: 3519, provinceID: 35, name: 'Madiun', type: 'Kabupaten' as const },
  { id: 3520, provinceID: 35, name: 'Magetan', type: 'Kabupaten' as const },
  { id: 3521, provinceID: 35, name: 'Ngawi', type: 'Kabupaten' as const },
  { id: 3522, provinceID: 35, name: 'Bojonegoro', type: 'Kabupaten' as const },
  { id: 3523, provinceID: 35, name: 'Tuban', type: 'Kabupaten' as const },
  { id: 3524, provinceID: 35, name: 'Lamongan', type: 'Kabupaten' as const },
  { id: 3525, provinceID: 35, name: 'Gresik', type: 'Kabupaten' as const },
  { id: 3526, provinceID: 35, name: 'Bangkalan', type: 'Kabupaten' as const },
  { id: 3527, provinceID: 35, name: 'Sampang', type: 'Kabupaten' as const },
  { id: 3528, provinceID: 35, name: 'Pamekasan', type: 'Kabupaten' as const },
  { id: 3529, provinceID: 35, name: 'Sumenep', type: 'Kabupaten' as const },
  { id: 3571, provinceID: 35, name: 'Kediri', type: 'Kota' as const },
  { id: 3572, provinceID: 35, name: 'Blitar', type: 'Kota' as const },
  { id: 3573, provinceID: 35, name: 'Malang', type: 'Kota' as const },
  { id: 3574, provinceID: 35, name: 'Probolinggo', type: 'Kota' as const },
  { id: 3575, provinceID: 35, name: 'Pasuruan', type: 'Kota' as const },
  { id: 3576, provinceID: 35, name: 'Mojokerto', type: 'Kota' as const },
  { id: 3577, provinceID: 35, name: 'Madiun', type: 'Kota' as const },
  { id: 3578, provinceID: 35, name: 'Surabaya', type: 'Kota' as const },
  { id: 3579, provinceID: 35, name: 'Batu', type: 'Kota' as const },
  { id: 3601, provinceID: 36, name: 'Pandeglang', type: 'Kabupaten' as const },
  { id: 3602, provinceID: 36, name: 'Lebak', type: 'Kabupaten' as const },
  { id: 3603, provinceID: 36, name: 'Tangerang', type: 'Kabupaten' as const },
  { id: 3604, provinceID: 36, name: 'Serang', type: 'Kabupaten' as const },
  { id: 3671, provinceID: 36, name: 'Tangerang', type: 'Kota' as const },
  { id: 3672, provinceID: 36, name: 'Cilegon', type: 'Kota' as const },
  { id: 3673, provinceID: 36, name: 'Serang', type: 'Kota' as const },
  { id: 3674, provinceID: 36, name: 'Tangerang Selatan', type: 'Kota' as const },
  { id: 5101, provinceID: 51, name: 'Jembrana', type: 'Kabupaten' as const },
  { id: 5102, provinceID: 51, name: 'Tabanan', type: 'Kabupaten' as const },
  { id: 5103, provinceID: 51, name: 'Badung', type: 'Kabupaten' as const },
  { id: 5104, provinceID: 51, name: 'Gianyar', type: 'Kabupaten' as const },
  { id: 5105, provinceID: 51, name: 'Klungkung', type: 'Kabupaten' as const },
  { id: 5106, provinceID: 51, name: 'Bangli', type: 'Kabupaten' as const },
  { id: 5107, provinceID: 51, name: 'Karang Asem', type: 'Kabupaten' as const },
  { id: 5108, provinceID: 51, name: 'Buleleng', type: 'Kabupaten' as const },
  { id: 5171, provinceID: 51, name: 'Denpasar', type: 'Kota' as const },
  { id: 5201, provinceID: 52, name: 'Lombok Barat', type: 'Kabupaten' as const },
  { id: 5202, provinceID: 52, name: 'Lombok Tengah', type: 'Kabupaten' as const },
  { id: 5203, provinceID: 52, name: 'Lombok Timur', type: 'Kabupaten' as const },
  { id: 5204, provinceID: 52, name: 'Sumbawa', type: 'Kabupaten' as const },
  { id: 5205, provinceID: 52, name: 'Dompu', type: 'Kabupaten' as const },
  { id: 5206, provinceID: 52, name: 'Bima', type: 'Kabupaten' as const },
  { id: 5207, provinceID: 52, name: 'Sumbawa Barat', type: 'Kabupaten' as const },
  { id: 5208, provinceID: 52, name: 'Lombok Utara', type: 'Kabupaten' as const },
  { id: 5271, provinceID: 52, name: 'Mataram', type: 'Kota' as const },
  { id: 5272, provinceID: 52, name: 'Bima', type: 'Kota' as const },
  { id: 5301, provinceID: 53, name: 'Sumba Barat', type: 'Kabupaten' as const },
  { id: 5302, provinceID: 53, name: 'Sumba Timur', type: 'Kabupaten' as const },
  { id: 5303, provinceID: 53, name: 'Kupang', type: 'Kabupaten' as const },
  { id: 5304, provinceID: 53, name: 'Timor Tengah Selatan', type: 'Kabupaten' as const },
  { id: 5305, provinceID: 53, name: 'Timor Tengah Utara', type: 'Kabupaten' as const },
  { id: 5306, provinceID: 53, name: 'Belu', type: 'Kabupaten' as const },
  { id: 5307, provinceID: 53, name: 'Alor', type: 'Kabupaten' as const },
  { id: 5308, provinceID: 53, name: 'Flores Timur', type: 'Kabupaten' as const },
  { id: 5309, provinceID: 53, name: 'Sikka', type: 'Kabupaten' as const },
  { id: 5310, provinceID: 53, name: 'Ende', type: 'Kabupaten' as const },
  { id: 5311, provinceID: 53, name: 'Ngada', type: 'Kabupaten' as const },
  { id: 5312, provinceID: 53, name: 'Manggarai', type: 'Kabupaten' as const },
  { id: 5313, provinceID: 53, name: 'Rote Ndao', type: 'Kabupaten' as const },
  { id: 5314, provinceID: 53, name: 'Manggarai Barat', type: 'Kabupaten' as const },
  { id: 5315, provinceID: 53, name: 'Sumba Tengah', type: 'Kabupaten' as const },
  { id: 5316, provinceID: 53, name: 'Sumba Barat Daya', type: 'Kabupaten' as const },
  { id: 5317, provinceID: 53, name: 'Nagekeo', type: 'Kabupaten' as const },
  { id: 5318, provinceID: 53, name: 'Manggarai Timur', type: 'Kabupaten' as const },
  { id: 5319, provinceID: 53, name: 'Sabu Raijua', type: 'Kabupaten' as const },
  { id: 5320, provinceID: 53, name: 'Malaka', type: 'Kabupaten' as const },
  { id: 5371, provinceID: 53, name: 'Kupang', type: 'Kota' as const },
  { id: 6101, provinceID: 61, name: 'Sambas', type: 'Kabupaten' as const },
  { id: 6102, provinceID: 61, name: 'Mempawah', type: 'Kabupaten' as const },
  { id: 6103, provinceID: 61, name: 'Sanggau', type: 'Kabupaten' as const },
  { id: 6104, provinceID: 61, name: 'Ketapang', type: 'Kabupaten' as const },
  { id: 6105, provinceID: 61, name: 'Sintang', type: 'Kabupaten' as const },
  { id: 6106, provinceID: 61, name: 'Kapuas Hulu', type: 'Kabupaten' as const },
  { id: 6107, provinceID: 61, name: 'Bengkayang', type: 'Kabupaten' as const },
  { id: 6108, provinceID: 61, name: 'Landak', type: 'Kabupaten' as const },
  { id: 6109, provinceID: 61, name: 'Sekadau', type: 'Kabupaten' as const },
  { id: 6110, provinceID: 61, name: 'Melawi', type: 'Kabupaten' as const },
  { id: 6111, provinceID: 61, name: 'Kayong Utara', type: 'Kabupaten' as const },
  { id: 6112, provinceID: 61, name: 'Kubu Raya', type: 'Kabupaten' as const },
  { id: 6171, provinceID: 61, name: 'Pontianak', type: 'Kota' as const },
  { id: 6172, provinceID: 61, name: 'Singkawang', type: 'Kota' as const },
  { id: 6201, provinceID: 62, name: 'Kotawaringin Barat', type: 'Kabupaten' as const },
  { id: 6202, provinceID: 62, name: 'Kotawaringin Timur', type: 'Kabupaten' as const },
  { id: 6203, provinceID: 62, name: 'Kapuas', type: 'Kabupaten' as const },
  { id: 6204, provinceID: 62, name: 'Barito Selatan', type: 'Kabupaten' as const },
  { id: 6205, provinceID: 62, name: 'Barito Utara', type: 'Kabupaten' as const },
  { id: 6206, provinceID: 62, name: 'Sukamara', type: 'Kabupaten' as const },
  { id: 6207, provinceID: 62, name: 'Lamandau', type: 'Kabupaten' as const },
  { id: 6208, provinceID: 62, name: 'Seruyan', type: 'Kabupaten' as const },
  { id: 6209, provinceID: 62, name: 'Katingan', type: 'Kabupaten' as const },
  { id: 6210, provinceID: 62, name: 'Pulang Pisau', type: 'Kabupaten' as const },
  { id: 6211, provinceID: 62, name: 'Gunung Mas', type: 'Kabupaten' as const },
  { id: 6212, provinceID: 62, name: 'Barito Timur', type: 'Kabupaten' as const },
  { id: 6213, provinceID: 62, name: 'Murung Raya', type: 'Kabupaten' as const },
  { id: 6271, provinceID: 62, name: 'Palangka Raya', type: 'Kota' as const },
  { id: 6301, provinceID: 63, name: 'Tanah Laut', type: 'Kabupaten' as const },
  { id: 6302, provinceID: 63, name: 'Kota Baru', type: 'Kabupaten' as const },
  { id: 6303, provinceID: 63, name: 'Banjar', type: 'Kabupaten' as const },
  { id: 6304, provinceID: 63, name: 'Barito Kuala', type: 'Kabupaten' as const },
  { id: 6305, provinceID: 63, name: 'Tapin', type: 'Kabupaten' as const },
  { id: 6306, provinceID: 63, name: 'Hulu Sungai Selatan', type: 'Kabupaten' as const },
  { id: 6307, provinceID: 63, name: 'Hulu Sungai Tengah', type: 'Kabupaten' as const },
  { id: 6308, provinceID: 63, name: 'Hulu Sungai Utara', type: 'Kabupaten' as const },
  { id: 6309, provinceID: 63, name: 'Tabalong', type: 'Kabupaten' as const },
  { id: 6310, provinceID: 63, name: 'Tanah Bumbu', type: 'Kabupaten' as const },
  { id: 6311, provinceID: 63, name: 'Balangan', type: 'Kabupaten' as const },
  { id: 6371, provinceID: 63, name: 'Banjarmasin', type: 'Kota' as const },
  { id: 6372, provinceID: 63, name: 'Banjarbaru', type: 'Kota' as const },
  { id: 6401, provinceID: 64, name: 'Paser', type: 'Kabupaten' as const },
  { id: 6402, provinceID: 64, name: 'Kutai Barat', type: 'Kabupaten' as const },
  { id: 6403, provinceID: 64, name: 'Kutai Kartanegara', type: 'Kabupaten' as const },
  { id: 6404, provinceID: 64, name: 'Kutai Timur', type: 'Kabupaten' as const },
  { id: 6405, provinceID: 64, name: 'Berau', type: 'Kabupaten' as const },
  { id: 6409, provinceID: 64, name: 'Penajam Paser Utara', type: 'Kabupaten' as const },
  { id: 6471, provinceID: 64, name: 'Balikpapan', type: 'Kota' as const },
  { id: 6472, provinceID: 64, name: 'Samarinda', type: 'Kota' as const },
  { id: 6474, provinceID: 64, name: 'Bontang', type: 'Kota' as const },
  { id: 6501, provinceID: 65, name: 'Malinau', type: 'Kabupaten' as const },
  { id: 6502, provinceID: 65, name: 'Bulungan', type: 'Kabupaten' as const },
  { id: 6503, provinceID: 65, name: 'Tana Tidung', type: 'Kabupaten' as const },
  { id: 6504, provinceID: 65, name: 'Nunukan', type: 'Kabupaten' as const },
  { id: 6571, provinceID: 65, name: 'Tarakan', type: 'Kota' as const },
  { id: 7101, provinceID: 71, name: 'Bolaang Mongondow', type: 'Kabupaten' as const },
  { id: 7102, provinceID: 71, name: 'Minahasa', type: 'Kabupaten' as const },
  { id: 7103, provinceID: 71, name: 'Kepulauan Sangihe', type: 'Kabupaten' as const },
  { id: 7104, provinceID: 71, name: 'Kepulauan Talaud', type: 'Kabupaten' as const },
  { id: 7105, provinceID: 71, name: 'Minahasa Selatan', type: 'Kabupaten' as const },
  { id: 7106, provinceID: 71, name: 'Minahasa Utara', type: 'Kabupaten' as const },
  { id: 7107, provinceID: 71, name: 'Bolaang Mongondow Utara', type: 'Kabupaten' as const },
  { id: 7108, provinceID: 71, name: 'Siau Tagulandang Biaro (Sitaro)', type: 'Kabupaten' as const },
  { id: 7109, provinceID: 71, name: 'Minahasa Tenggara', type: 'Kabupaten' as const },
  { id: 7110, provinceID: 71, name: 'Bolaang Mongondow Selatan', type: 'Kabupaten' as const },
  { id: 7111, provinceID: 71, name: 'Bolaang Mongondow Timur', type: 'Kabupaten' as const },
  { id: 7171, provinceID: 71, name: 'Manado', type: 'Kota' as const },
  { id: 7172, provinceID: 71, name: 'Bitung', type: 'Kota' as const },
  { id: 7173, provinceID: 71, name: 'Tomohon', type: 'Kota' as const },
  { id: 7174, provinceID: 71, name: 'Kotamobagu', type: 'Kota' as const },
  { id: 7201, provinceID: 72, name: 'Banggai', type: 'Kabupaten' as const },
  { id: 7202, provinceID: 72, name: 'Poso', type: 'Kabupaten' as const },
  { id: 7203, provinceID: 72, name: 'Donggala', type: 'Kabupaten' as const },
  { id: 7204, provinceID: 72, name: 'Toli-Toli', type: 'Kabupaten' as const },
  { id: 7205, provinceID: 72, name: 'Buol', type: 'Kabupaten' as const },
  { id: 7206, provinceID: 72, name: 'Morowali', type: 'Kabupaten' as const },
  { id: 7207, provinceID: 72, name: 'Banggai Kepulauan', type: 'Kabupaten' as const },
  { id: 7208, provinceID: 72, name: 'Parigi Moutong', type: 'Kabupaten' as const },
  { id: 7209, provinceID: 72, name: 'Tojo Una-Una', type: 'Kabupaten' as const },
  { id: 7210, provinceID: 72, name: 'Sigi', type: 'Kabupaten' as const },
  { id: 7271, provinceID: 72, name: 'Palu', type: 'Kota' as const },
  { id: 7301, provinceID: 73, name: 'Kepulauan Selayar', type: 'Kabupaten' as const },
  { id: 7302, provinceID: 73, name: 'Bulukumba', type: 'Kabupaten' as const },
  { id: 7303, provinceID: 73, name: 'Bantaeng', type: 'Kabupaten' as const },
  { id: 7304, provinceID: 73, name: 'Jeneponto', type: 'Kabupaten' as const },
  { id: 7305, provinceID: 73, name: 'Takalar', type: 'Kabupaten' as const },
  { id: 7306, provinceID: 73, name: 'Gowa', type: 'Kabupaten' as const },
  { id: 7307, provinceID: 73, name: 'Sinjai', type: 'Kabupaten' as const },
  { id: 7308, provinceID: 73, name: 'Bone', type: 'Kabupaten' as const },
  { id: 7309, provinceID: 73, name: 'Maros', type: 'Kabupaten' as const },
  { id: 7310, provinceID: 73, name: 'Pangkajene Dan Kepulauan', type: 'Kabupaten' as const },
  { id: 7311, provinceID: 73, name: 'Barru', type: 'Kabupaten' as const },
  { id: 7312, provinceID: 73, name: 'Soppeng', type: 'Kabupaten' as const },
  { id: 7313, provinceID: 73, name: 'Wajo', type: 'Kabupaten' as const },
  { id: 7314, provinceID: 73, name: 'Sidenreng Rappang', type: 'Kabupaten' as const },
  { id: 7315, provinceID: 73, name: 'Pinrang', type: 'Kabupaten' as const },
  { id: 7316, provinceID: 73, name: 'Enrekang', type: 'Kabupaten' as const },
  { id: 7317, provinceID: 73, name: 'Luwu', type: 'Kabupaten' as const },
  { id: 7318, provinceID: 73, name: 'Tana Toraja', type: 'Kabupaten' as const },
  { id: 7322, provinceID: 73, name: 'Luwu Utara', type: 'Kabupaten' as const },
  { id: 7325, provinceID: 73, name: 'Luwu Timur', type: 'Kabupaten' as const },
  { id: 7326, provinceID: 73, name: 'Toraja Utara', type: 'Kabupaten' as const },
  { id: 7371, provinceID: 73, name: 'Makassar', type: 'Kota' as const },
  { id: 7372, provinceID: 73, name: 'Parepare', type: 'Kota' as const },
  { id: 7373, provinceID: 73, name: 'Palu', type: 'Kota' as const },
  { id: 7401, provinceID: 74, name: 'Buton', type: 'Kabupaten' as const },
  { id: 7402, provinceID: 74, name: 'Muna', type: 'Kabupaten' as const },
  { id: 7403, provinceID: 74, name: 'Konawe', type: 'Kabupaten' as const },
  { id: 7404, provinceID: 74, name: 'Kolaka', type: 'Kabupaten' as const },
  { id: 7405, provinceID: 74, name: 'Konawe Selatan', type: 'Kabupaten' as const },
  { id: 7406, provinceID: 74, name: 'Bombana', type: 'Kabupaten' as const },
  { id: 7407, provinceID: 74, name: 'Wakatobi', type: 'Kabupaten' as const },
  { id: 7408, provinceID: 74, name: 'Kolaka Utara', type: 'Kabupaten' as const },
  { id: 7409, provinceID: 74, name: 'Buton Utara', type: 'Kabupaten' as const },
  { id: 7410, provinceID: 74, name: 'Konawe Utara', type: 'Kabupaten' as const },
  { id: 7411, provinceID: 74, name: 'Kolaka Timur', type: 'Kabupaten' as const },
  { id: 7412, provinceID: 74, name: 'Konawe Kepulauan', type: 'Kabupaten' as const },
  { id: 7413, provinceID: 74, name: 'Muna Barat', type: 'Kabupaten' as const },
  { id: 7414, provinceID: 74, name: 'Buton Tengah', type: 'Kabupaten' as const },
  { id: 7415, provinceID: 74, name: 'Buton Selatan', type: 'Kabupaten' as const },
  { id: 7471, provinceID: 74, name: 'Kendari', type: 'Kota' as const },
  { id: 7472, provinceID: 74, name: 'Baubau', type: 'Kota' as const },
  { id: 7501, provinceID: 75, name: 'Boalemo', type: 'Kabupaten' as const },
  { id: 7502, provinceID: 75, name: 'Gorontalo', type: 'Kabupaten' as const },
  { id: 7503, provinceID: 75, name: 'Pohuwato', type: 'Kabupaten' as const },
  { id: 7504, provinceID: 75, name: 'Bone Bolango', type: 'Kabupaten' as const },
  { id: 7505, provinceID: 75, name: 'Gorontalo Utara', type: 'Kabupaten' as const },
  { id: 7571, provinceID: 75, name: 'Gorontalo', type: 'Kota' as const },
  { id: 7601, provinceID: 76, name: 'Majene', type: 'Kabupaten' as const },
  { id: 7602, provinceID: 76, name: 'Polewali Mandar', type: 'Kabupaten' as const },
  { id: 7603, provinceID: 76, name: 'Mamasa', type: 'Kabupaten' as const },
  { id: 7604, provinceID: 76, name: 'Mamuju', type: 'Kabupaten' as const },
  { id: 7605, provinceID: 76, name: 'Mamuju Utara', type: 'Kabupaten' as const },
  { id: 7606, provinceID: 76, name: 'Mamuju Tengah', type: 'Kabupaten' as const },
  { id: 8101, provinceID: 81, name: 'Maluku Tenggara Barat', type: 'Kabupaten' as const },
  { id: 8102, provinceID: 81, name: 'Maluku Tenggara', type: 'Kabupaten' as const },
  { id: 8103, provinceID: 81, name: 'Maluku Tengah', type: 'Kabupaten' as const },
  { id: 8104, provinceID: 81, name: 'Buru', type: 'Kabupaten' as const },
  { id: 8105, provinceID: 81, name: 'Kepulauan Aru', type: 'Kabupaten' as const },
  { id: 8106, provinceID: 81, name: 'Seram Bagian Barat', type: 'Kabupaten' as const },
  { id: 8107, provinceID: 81, name: 'Seram Bagian Timur', type: 'Kabupaten' as const },
  { id: 8108, provinceID: 81, name: 'Maluku Barat Daya', type: 'Kabupaten' as const },
  { id: 8109, provinceID: 81, name: 'Buru Selatan', type: 'Kabupaten' as const },
  { id: 8171, provinceID: 81, name: 'Ambon', type: 'Kota' as const },
  { id: 8172, provinceID: 81, name: 'Tual', type: 'Kota' as const },
  { id: 8201, provinceID: 82, name: 'Halmahera Barat', type: 'Kabupaten' as const },
  { id: 8202, provinceID: 82, name: 'Halmahera Tengah', type: 'Kabupaten' as const },
  { id: 8203, provinceID: 82, name: 'Kepulauan Sula', type: 'Kabupaten' as const },
  { id: 8204, provinceID: 82, name: 'Halmahera Selatan', type: 'Kabupaten' as const },
  { id: 8205, provinceID: 82, name: 'Halmahera Utara', type: 'Kabupaten' as const },
  { id: 8206, provinceID: 82, name: 'Halmahera Timur', type: 'Kabupaten' as const },
  { id: 8207, provinceID: 82, name: 'Pulau Morotai', type: 'Kabupaten' as const },
  { id: 8208, provinceID: 82, name: 'Pulau Taliabu', type: 'Kabupaten' as const },
  { id: 8271, provinceID: 82, name: 'Ternate', type: 'Kota' as const },
  { id: 8272, provinceID: 82, name: 'Tidore Kepulauan', type: 'Kota' as const },
  { id: 9116, provinceID: 91, name: 'Sarmi', type: 'Kabupaten' as const },
  { id: 9117, provinceID: 91, name: 'Keerom', type: 'Kabupaten' as const },
  { id: 9118, provinceID: 91, name: 'Waropen', type: 'Kabupaten' as const },
  { id: 9119, provinceID: 91, name: 'Supiori', type: 'Kabupaten' as const },
  { id: 9120, provinceID: 91, name: 'Mamberamo Raya', type: 'Kabupaten' as const },
  { id: 9171, provinceID: 91, name: 'Jayapura', type: 'Kota' as const },
  { id: 9201, provinceID: 92, name: 'Fakfak', type: 'Kabupaten' as const },
  { id: 9202, provinceID: 92, name: 'Kaimana', type: 'Kabupaten' as const },
  { id: 9203, provinceID: 92, name: 'Teluk Wondama', type: 'Kabupaten' as const },
  { id: 9204, provinceID: 92, name: 'Teluk Bintuni', type: 'Kabupaten' as const },
  { id: 9205, provinceID: 92, name: 'Manokwari', type: 'Kabupaten' as const },
  { id: 9206, provinceID: 92, name: 'Sorong Selatan', type: 'Kabupaten' as const },
  { id: 9207, provinceID: 92, name: 'Sorong', type: 'Kabupaten' as const },
  { id: 9208, provinceID: 92, name: 'Raja Ampat', type: 'Kabupaten' as const },
  { id: 9209, provinceID: 92, name: 'Tambrauw', type: 'Kabupaten' as const },
  { id: 9210, provinceID: 92, name: 'Maybrat', type: 'Kabupaten' as const },
  { id: 9211, provinceID: 92, name: 'Manokwari Selatan', type: 'Kabupaten' as const },
  { id: 9212, provinceID: 92, name: 'Pegunungan Arfak', type: 'Kabupaten' as const },
  { id: 9271, provinceID: 92, name: 'Sorong', type: 'Kota' as const },
  { id: 9301, provinceID: 93, name: 'Asmat', type: 'Kabupaten' as const },
  { id: 9302, provinceID: 93, name: 'Boven Digoel', type: 'Kabupaten' as const },
  { id: 9303, provinceID: 93, name: 'Mappi', type: 'Kabupaten' as const },
  { id: 9304, provinceID: 93, name: 'Merauke', type: 'Kabupaten' as const },
  { id: 9401, provinceID: 94, name: 'Deiyai (Deliyai)', type: 'Kabupaten' as const },
  { id: 9402, provinceID: 94, name: 'Dogiyai', type: 'Kabupaten' as const },
  { id: 9403, provinceID: 94, name: 'Intan Jaya', type: 'Kabupaten' as const },
  { id: 9404, provinceID: 94, name: 'Mimika', type: 'Kabupaten' as const },
  { id: 9408, provinceID: 94, name: 'Nabire', type: 'Kabupaten' as const },
  { id: 9409, provinceID: 94, name: 'Paniai', type: 'Kabupaten' as const },
  { id: 9410, provinceID: 94, name: 'Puncak', type: 'Kabupaten' as const },
  { id: 9411, provinceID: 94, name: 'Puncak Jaya', type: 'Kabupaten' as const },
  { id: 9501, provinceID: 95, name: 'Jayawijaya', type: 'Kabupaten' as const },
  { id: 9502, provinceID: 95, name: 'Lanny Jaya', type: 'Kabupaten' as const },
  { id: 9503, provinceID: 95, name: 'Mamberamo Tengah', type: 'Kabupaten' as const },
  { id: 9504, provinceID: 95, name: 'Nduga', type: 'Kabupaten' as const },
  { id: 9505, provinceID: 95, name: 'Pegunungan Bintang', type: 'Kabupaten' as const },
  { id: 9506, provinceID: 95, name: 'Tolikara', type: 'Kabupaten' as const },
  { id: 9507, provinceID: 95, name: 'Yahukimo', type: 'Kabupaten' as const },
  { id: 9508, provinceID: 95, name: 'Yalimo', type: 'Kabupaten' as const },
  { id: 9601, provinceID: 96, name: 'Maybrat', type: 'Kabupaten' as const },
  { id: 9602, provinceID: 96, name: 'Raja Ampat', type: 'Kabupaten' as const },
  { id: 9603, provinceID: 96, name: 'Sorong', type: 'Kabupaten' as const },
  { id: 9604, provinceID: 96, name: 'Sorong Selatan', type: 'Kabupaten' as const },
  { id: 9605, provinceID: 96, name: 'Tambrauw', type: 'Kabupaten' as const },
  { id: 9606, provinceID: 96, name: 'Sorong', type: 'Kota' as const },
]

export function getCitiesByProvinceID(provinceID?: number): City[] {
  return provinceID ? INDONESIAN_CITIES.filter((city) => city.provinceID === provinceID) : INDONESIAN_CITIES
}

export function getProvinceByID(provinceID: number): Province | undefined {
  return INDONESIAN_PROVINCES.find((province) => province.id === provinceID)
}

export function getCityByID(cityID: number): City | undefined {
  return INDONESIAN_CITIES.find((city) => city.id === cityID)
}

export function getProvinceNameByID(provinceID: string | number): string {
  const id = typeof provinceID === 'string' ? Number(provinceID) : provinceID
  return INDONESIAN_PROVINCES.find((p) => p.id === id)?.name ?? provinceID.toString()
}

export function getCityNameByID(cityID: string | number): string {
  const id = typeof cityID === 'string' ? Number(cityID) : cityID
  return INDONESIAN_CITIES.find((c) => c.id === id)?.name ?? cityID.toString()
}
